[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/producteurs-productrices/2026-porc/index.html"
to = "/produits-et-contrats/2026-porc/"

[[redirects]]
from = "/producteurs-productrices/index.html"
to = "/produits-et-contrats/"

[[redirects]]
from = "/producteurs-productrices/2026-kiwis/index.html"
to = "/produits-et-contrats/2026-kiwis/"

[[redirects]]
from = "/producteurs-productrices/2026-agrumes-corses/index.html"
to = "/produits-et-contrats/2026-agrumes/"

[[redirects]]
from = "/producteurs-productrices/2026-pommes/index.html"
to = "/produits-et-contrats/2026-pommes/"

[[redirects]]
from = "/projets/index.html"
to = "/produits-et-contrats/"

[[redirects]]
from = "/producteurs-productrices/2026-tisanes-et-aromates/index.html"
to = "/produits-et-contrats/2026-tisanes-et-aromates/"

[[redirects]]
from = "/producteurs-productrices/2026-oranges-corses/index.html"
to = "/produits-et-contrats/2026-oranges/"

[[redirects]]
from = "/produits-et-contrats/2026-oranges-corses/index.html"
to = "/produits-et-contrats/2026-oranges/"

[[redirects]]
from = "/producteurs-productrices/2026-brebis/index.html"
to = "/produits-et-contrats/2026-brebis/"

[[redirects]]
from = "/producteurs-productrices/2026-pain/index.html"
to = "/produits-et-contrats/2026-pain/"

[[redirects]]
from = "/producteurs-productrices/2026-clementines-de-noel/index.html"
to = "/produits-et-contrats/2026-clementines-de-noel/"

[[redirects]]
from = "/producteurs-productrices/2026-fromage-de-chevre/index.html"
to = "/produits-et-contrats/2026-fromage-de-chevre/"

[[redirects]]
from = "/producteurs-productrices/2026-miel/index.html"
to = "/produits-et-contrats/2026-miel/"

[[redirects]]
from = "/producteurs-productrices/2026-legumes/index.html"
to = "/produits-et-contrats/2026-legumes/"

[[redirects]]
from = "/produits-et-contrats/2026-agrumes-corses/index.html"
to = "/produits-et-contrats/2026-agrumes/"

[[redirects]]
from = "/producteurs-productrices/2026-fraises/index.html"
to = "/produits-et-contrats/2026-fraises/"

[[redirects]]
from = "/producteurs-productrices/2026-creme-de-marron/index.html"
to = "/produits-et-contrats/2026-creme-de-marron/"

