[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/producteurs-productrices/index.html"
to = "/produits-et-contrats/"

[[redirects]]
from = "/producteurs-productrices/2026-agrumes-corses/index.html"
to = "/produits-et-contrats/2026-agrumes-corses/"

[[redirects]]
from = "/projets/index.html"
to = "/produits-et-contrats/"

[[redirects]]
from = "/producteurs-productrices/2026-brebis/index.html"
to = "/produits-et-contrats/2026-brebis/"

[[redirects]]
from = "/producteurs-productrices/2026-clementines-de-noel/index.html"
to = "/produits-et-contrats/2026-clementines-de-noel/"

[[redirects]]
from = "/producteurs-productrices/2026-fraises/index.html"
to = "/produits-et-contrats/2026-fraises/"

[[redirects]]
from = "/producteurs-productrices/2026-creme-de-marron/index.html"
to = "/produits-et-contrats/2026-creme-de-marron/"

